import { Inter } from 'next/font/google'

import './globals.css'

import getCurrentUser from './helpers/getCurrentuser'
import Navbar from '@/components/navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js v13.4 Boilerplate',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar currentUser={currentUser} />
        <main>{children}</main>
      </body>
    </html>
  )
}
